apiVersion: v2
name: Istio
description: Helm chart for the istio service mesh
type: application
version: 0.1.0

dependencies:
  - name: base
    version: 1.30.3
    repository: https://istio-release.storage.googleapis.com/charts
    condition: base.enabled
  - name: istiod
    version: 1.30.3
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istiod.enabled
  - name: gateway
    version: 1.30.3
    repository: https://istio-release.storage.googleapis.com/charts
    condition: gateway.enabled