###############################################################################
# Istio Base
#
# Installs Istio CRDs.
###############################################################################

base:
  enabled: true

###############################################################################
# Istiod
#
# Istio control plane.
###############################################################################

istiod:
  enabled: true

###############################################################################
# Istio Ingress Gateway
#
# External entry point into the mesh.
###############################################################################

gateway:
  enabled: true
