apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-expose
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MrRespicio/mrespicio.lab.git
    targetRevision: main
    path: rke2-services/rke2-configurations/helm-charts/argocd-expose
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true