apiVersion: v2
name: istiod
description: Istio Control Plane
type: application
version: 0.1.0

dependencies:
  - name: istiod
    version: 1.30.3
    repository: https://istio-release.storage.googleapis.com/charts